`timescale 1ns/1ps

module image_buffer #(

    parameter IMAGE_WIDTH  = 8,
    parameter IMAGE_HEIGHT = 8,
    parameter ADDR_WIDTH   = 6

)(

    input  logic                  clk,
    input  logic                  rst,

    // =========================================================
    // WRITE PORT
    // Used later by CPU/UART to load image pixels
    // =========================================================

    input  logic                  wr_en,
    input  logic [ADDR_WIDTH-1:0] wr_addr,
    input  logic signed [7:0]     wr_data,


    // =========================================================
    // READ PORT
    // Used by sliding-window generator
    // =========================================================

    input  logic [ADDR_WIDTH-1:0] rd_addr,
    output logic signed [7:0]     rd_data

);


    localparam DEPTH = IMAGE_WIDTH * IMAGE_HEIGHT;


    // =========================================================
    // IMAGE MEMORY
    //
    // For default 8x8 image:
    // 64 locations x 8 bits
    // =========================================================

    logic signed [7:0] memory [0:DEPTH-1];


    // =========================================================
    // WRITE
    // =========================================================

    always_ff @(posedge clk) begin

        if (wr_en) begin

            memory[wr_addr] <= wr_data;

        end

    end


    // =========================================================
    // ASYNCHRONOUS READ
    //
    // rd_addr is generated by sliding_window_handshake.
    // The pixel at that address is immediately available.
    // =========================================================

    always_comb begin

        if (rd_addr < DEPTH)
            rd_data = memory[rd_addr];

        else
            rd_data = 8'sd0;

    end


endmodule
