module stride_control (

    input logic clk,
    input logic reset,

    // Valid 3x3 window from stream_window_3x3
    input logic window_valid,

    // New input-channel plane starts
    input logic channel_start,

    // Number of valid stride-1 convolution positions
    //
    // For valid 3x3:
    // base_output_width  = image_width  - 2
    // base_output_height = image_height - 2
    input logic [15:0] base_output_width,
    input logic [15:0] base_output_height,

    // Supported:
    // 1 = normal convolution
    // 2 = stride-2 convolution
    input logic [1:0] stride,

    // Window accepted by convolution engine
    output logic stride_window_valid,

    // Coordinates in the stride-1 output grid
    output logic [15:0] window_row,
    output logic [15:0] window_col
);


    logic [15:0] row_counter;
    logic [15:0] col_counter;


    // =========================================================
    // ACCEPT / DROP CURRENT WINDOW
    // =========================================================

    always_comb begin

        stride_window_valid =
            1'b0;


        if (window_valid) begin

            case (stride)

                // =============================================
                // STRIDE 1
                // =============================================

                2'd1: begin

                    stride_window_valid =
                        1'b1;

                end


                // =============================================
                // STRIDE 2
                //
                // Keep:
                //
                // row 0,2,4,...
                // col 0,2,4,...
                // =============================================

                2'd2: begin

                    if (
                        (row_counter[0] == 1'b0)
                        &&
                        (col_counter[0] == 1'b0)
                    ) begin

                        stride_window_valid =
                            1'b1;

                    end

                end


                // =============================================
                // SAFETY
                //
                // Treat unsupported values as stride 1.
                // =============================================

                default: begin

                    stride_window_valid =
                        1'b1;

                end

            endcase

        end

    end


    // =========================================================
    // WINDOW COORDINATE TRACKER
    //
    // This counts EVERY stride-1 window generated by the
    // streaming window block.
    // =========================================================

    always_ff @(posedge clk) begin

        if (reset) begin

            row_counter <=
                16'd0;

            col_counter <=
                16'd0;

            window_row <=
                16'd0;

            window_col <=
                16'd0;

        end

        else begin

            if (channel_start) begin

                row_counter <=
                    16'd0;

                col_counter <=
                    16'd0;

            end


            if (window_valid) begin

                // Export coordinates belonging to this window.

                window_row <=
                    row_counter;

                window_col <=
                    col_counter;


                // =============================================
                // ADVANCE THROUGH STRIDE-1 OUTPUT GRID
                // =============================================

                if (
                    col_counter + 1
                    >=
                    base_output_width
                ) begin

                    col_counter <=
                        16'd0;


                    if (
                        row_counter + 1
                        >=
                        base_output_height
                    ) begin

                        row_counter <=
                            16'd0;

                    end

                    else begin

                        row_counter <=
                            row_counter + 1'b1;

                    end

                end

                else begin

                    col_counter <=
                        col_counter + 1'b1;

                end

            end

        end

    end


endmodule
